version: "3.2"
services:
  azure:
    image: docker.io/manibabu3732/azure
    ports:
      - "9091:80"
    deploy:
      replicas: 3
  gcp:
    image: docker.io/manibabu3732/gcp
    ports:
      - "9092:80"
    deploy:
      replicas: 2
  datascience:
    image: docker.io/manibabu3732/datascience
    ports:
      - "9093:80"
    deploy:
      replicas: 2
